{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-2412] Issue with network connection", "trace": "('/usr/lessons/tests/users/test_users.py', 20, 'Skipped: [ISSUE-2412] Issue with network connection')"}, "description": "\n    In this test we are checking that 1 == 1\n\n    ", "start": 1689717878680, "stop": 1689717878680, "uuid": "5e57f21a-e8f4-4c21-92b1-2d5b6f2cf578", "historyId": "19630dc244333b530cc14c893795ee5f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-2412] Issue with network connection')"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "87e95aac290a"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}